// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJL2NYRW8uhI1d5mm04WfRFvJ0tQKltEU',
    appId: '1:995375495621:web:b24cab8bd57a9763b273ac',
    messagingSenderId: '995375495621',
    projectId: 'health-care-app-c53bb',
    authDomain: 'health-care-app-c53bb.firebaseapp.com',
    databaseURL: 'https://health-care-app-c53bb-default-rtdb.firebaseio.com',
    storageBucket: 'health-care-app-c53bb.appspot.com',
    measurementId: 'G-4HQYR8SZ76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr3Djy5ztSfcMGG1oWJv8V-5Ye82FsXXs',
    appId: '1:995375495621:android:855100325ed7e04db273ac',
    messagingSenderId: '995375495621',
    projectId: 'health-care-app-c53bb',
    databaseURL: 'https://health-care-app-c53bb-default-rtdb.firebaseio.com',
    storageBucket: 'health-care-app-c53bb.appspot.com',
  );
}
